version: "3.8"

services:
  postgis:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

  geoserver:
    image: kartoza/geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver-config/data_dir:/opt/geoserver/data_dir
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    depends_on:
      - postgis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  init-db:
    image: postgres
    depends_on:
      - postgis
    environment:
      PGPASSWORD: docker
    entrypoint: sh
    command: >
      -c "echo 'Waiting for DB...';
      until pg_isready -h postgis -U docker -d postgres; do sleep 1; done;
      echo 'Running SQL...';
      echo \"
        CREATE EXTENSION IF NOT EXISTS postgis;
        CREATE TABLE IF NOT EXISTS my_lines (
          id SERIAL PRIMARY KEY,
          geom geometry(LineString, 3857)
        );
      \" | psql -h postgis -U docker -d postgres"
